### ISSUE TITLE
Embed Dynamic Libraries for Different Operating System [2 XMR]

### ISSUE THREAD

**Issue by buko** [woodser/monero-java#12]
It's worth investigating how one might build the dynamic library for different platforms and distribute that through Maven. Projects like [lmdbjava](https://github.com/lmdbjava/lmdbjava) and [native platform](https://github.com/adammurdoch/native-platform) all include significant native libraries but this is transparent to Java applications which need only declare dependencies on the Maven artifacts. Ideally, I think, there would be separate projects to build the publish the native library to Maven. Developers could use pre-built artifacts in Maven central or build their own. All these would then get sucked into the classpath by the core monero-java dependency and at runtime, depending on the OS, the right library would be loaded.

**Comment by woodser** [comment]
That would be great.  I welcome any outside help.

**Comment by woodser** [comment]
Bounty added to package the native libraries into the JAR which is portable across platforms.

The native libraries can be downloaded from the [latest release](https://github.com/woodser/monero-java/releases/tag/v0.8.13).

**Comment by woodser** [comment]
This issue is resolved in the latest release, so the native libraries are now distributed with the JAR file, and clients do not need to build them.

Thanks for the request almost 5 years ago! :)
