### ISSUE TITLE
convert MoneroTx extra to string

### ISSUE THREAD

**Issue by t-900-a** [woodser/monero-java#23]
I saw this in the todo.txt, wondering if this is still on the radar?
I'd like to complete it, but will need some direction. Not sure what to do with the int array. I thought it was hex, but hex has more than just integers.
Also what are your guys's thoughts on adding a function to add a string to the TX_EXTRA_TAG_PADDING field within tx extra?

**Comment by woodser** [comment]
Here is a [JavaScript utility](https://github.com/monero-ecosystem/monero-javascript/blob/c7b3682b341b2f73668259435a18f823d70bb335/src/main/js/utils/MoneroUtils.js#L80) which demonstrates converting a tx extra field to a string.

[C++ utilities](https://github.com/monero-project/monero/blob/d1cf16364fb1901c2940ce66024688ea3fe3fc48/src/cryptonote_basic/cryptonote_format_utils.cpp#L511) exist to modify and parse tx extra data.  Any of these methods can be exposed in Java or JavaScript if they're useful.

Background reading on how tx extra data is encoded: https://cryptonote.org/cns/cns005.txt

**Comment by woodser** [comment]
This method [creates an extra field](https://github.com/monero-project/monero/blob/d1cf16364fb1901c2940ce66024688ea3fe3fc48/src/wallet/wallet_rpc_server.cpp#L752) which is passed in to [tx creation](https://github.com/monero-project/monero/blob/d1cf16364fb1901c2940ce66024688ea3fe3fc48/src/wallet/wallet_rpc_server.cpp#L952).

Similar support could be added to the [tx creation method](https://github.com/woodser/monero-cpp-library/blob/2d2aadb493357ea4a4237243f0c2a886902ebd1a/src/wallet/monero_wallet_core.cpp#L1897) used by the Java and JavaScript libraries, so you can pass your custom extra data with the send request.

**Comment by woodser** [comment]
Closing, please re-open if still relevant.
