### ISSUE TITLE
XMR 两个子地址之间的转账 在交易中如何解析出来？？

### ISSUE THREAD

**Issue by miles-zhangdy** [woodser/monero-java#33]
这笔交易是一笔出金，接受地址和金额有办法解析出来么？谢谢！

**Comment by woodser** [comment]
I'm sorry I'm not able to understand well.

Please see [these methods](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/sending_funds.md) to withdraw funds.

After creating the transaction, you can get destination addresses and amounts like this:

```javascript
let tx = await wallet.createTx(...);
let destinations = tx.getOutgoingTransfer().getDestinations(); // destinations is only available from local wallet data, not recoverable from blockchain
for (let destination of destinations) {
  let address = destination.getAddress();
  let amount = destination.getAmount();
}
```

**Comment by miles-zhangdy** [comment]
> I'm sorry I'm not able to understand well.
> 
> After using [`createTx()`](https://moneroecosystem.org/monero-java/monero/wallet/MoneroWallet.html#createTx(monero.wallet.model.MoneroTxConfig)) to withdraw funds, you can get destination addresses and amounts like this:
> 
> ```java
> MoneroTxWallet tx = wallet.createTx(...);
> for (MoneroDestination : tx.getOutgoingTransfer().getDestinations()) { // destinations only available from local wallet data
>   String address = destination.getAddress();
>   BigInteger amount = destination.getAmount();
> }
> ```
> 
> Note that destination amount and addresses are only available from local wallet data and are not recoverable from the blockchain.

在转出的时候没有解析该信息，即该交易广播上链之后，对于扫描区块交易的时候，就是扫描哪些是入金到平台钱包地址的，如何可以解析接收地址和金额。


另外一个问题：转出时 如果需要找零，那找零地址是每次使用一个新地址 还是找零到固定地址？？

**Comment by woodser** [comment]
The destination addresses and amounts are not recoverable from scanning the blockchain. This information is only stored with your local wallet file where you sent the transaction.

Change always goes to your wallet's primary address (account 0, subaddress 0). On the blockchain, this appears as a unique address since Monero always uses one-time addresses on the blockchain.

**Comment by miles-zhangdy** [comment]
> The destination addresses and amounts are not recoverable from scanning the blockchain. This information is only stored with your local wallet file where you sent the transaction.
> 
> Change always goes to your wallet's primary address (account 0, subaddress 0). On the blockchain, this appears as a unique address since Monero always uses one-time addresses on the blockchain.

https://web.getmonero.org/resources/moneropedia/change.html

**Comment by woodser** [comment]
What is different from what I said? Change is always returned to the wallet's primary address.

**Comment by woodser** [comment]
Closing as stale.
