### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by bigBonSlime** [woodser/monero-java#57]
1) 
The first problem occurs at the 6th step of the building cpp-lib.
I am getting an error in the picture. If you need a more  detailed description, then I will reproduce the error and give details. For some reason, the project is built after deleting the build folder and restarting the build.
![image](https://github.com/monero-ecosystem/monero-java/assets/108625289/b60d27a4-7942-4bef-bb5e-4295908cc59c)
2)The second problem arises already at the stage of building the Java library itself. I am getting the following error:
```
[100%] Built target monero-cpp
-- MONERO_CPP:/home/user/Desktop/monero/monero-java/external/monero-cpp:/home/user/Desktop/monero/monero-java/external/monero-cpp
CMake Error at CMakeLists.txt:28 (include_directories):
  include_directories given empty-string as include directory.
```
Ubuntu 23.04

**Comment by woodser** [comment]
Looks like a problem building monero-project itself.

You should be able to `cd ./external/monero-cpp/external/monero-project` and `make release-static -j<numThreads>` to build monero-project independently and confirm you see the error.

Did you install monero-project dependencies from the monero-cpp instructions? That should install boost.

`
sudo apt update && sudo apt install build-essential cmake pkg-config libssl-dev libzmq3-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libpgm-dev qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler libudev-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-locale-dev libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-system-dev libboost-thread-dev python3 ccache
`

**Comment by woodser** [comment]
Closing as stale, and the issue is likely related to building monero-project itself.
