### ISSUE TITLE
Build issues linking libicuuc.a?

### ISSUE THREAD

**Issue by Thomas-de-Bock** [woodser/monero-java#71]
I'm trying to build the project which works fine right up until the end where I get the error:
[output.txt](https://github.com/woodser/monero-java/files/14077392/output.txt)

```
/usr/bin/ld: (.text+0x4b): undefined reference to `icu_74::UnicodeString::UnicodeString(char const*)'
/usr/bin/ld: (.text+0x54): undefined reference to `icu_74::TimeZone::createTimeZone(icu_74::UnicodeString const&)'
/usr/bin/ld: (.text+0x60): undefined reference to `icu_74::UnicodeString::~UnicodeString()'
/usr/bin/ld: /usr/lib/libboost_locale.a(time_zone.o): in function `boost::locale::impl_icu::get_time_zone(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]':
(.text.unlikely+0x5): undefined reference to `icu_74::UnicodeString::~UnicodeString()'
collect2: error: ld returned 1 exit status
make[3]: *** [src/simplewallet/CMakeFiles/simplewallet.dir/build.make:156: bin/monero-wallet-cli] Error 1
make[2]: *** [CMakeFiles/Makefile2:3328: src/simplewallet/CMakeFiles/simplewallet.dir/all] Error 2
make[1]: *** [Makefile:146: all] Error 2
```

With many similar icu_74 errors preceeding it.
I built the monero project just fine last time I remember, so wondering if this is an issue on my end or in the CMake files. 

Arch Linux x86_64
6.6.10-arch1-1

**Comment by woodser** [comment]
Does your monero-project build successfully?

i.e. `cd ./external/monero-cpp/external/monero-project` and e.g. `make release-static -j8`

That will tell us if it's something specific to the libraries.

**Comment by Thomas-de-Bock** [comment]
Oh it does not, I get the same errors, guess it is an issue on my end. Thank you.

**Comment by Thomas-de-Bock** [comment]
Hey, no matter what I try I can't seem to compile the monero project (even in a VM), which I desperately need so I can get the static `libmonero-java.so` file for an android project I'm working on. I would greatly appreciate it if you could send me a copy of this file, thank you.
