### ISSUE TITLE
Native libraries failing on Windows with `UnsatisfiedLinkError` [2 XMR]

### ISSUE THREAD

**Issue by woodser** [woodser/monero-java#82]
Currently, native libraries are built for Windows, producing these files:

- libmonero-cpp.dll
- libmonero-cpp.dll.a
- libmonero-java.dll
- libmonero-java.dll.a

However, using the native libraries results in an error when using JNI functions: "UnsatisfiedLinkError".

To reproduce the failure in a test:

1. On Windows, download [Visual Studio Code](https://code.visualstudio.com/) and install Java extensions.
2. Import the monero-java project into workspace.
3. [Build](https://github.com/woodser/monero-java?tab=readme-ov-file#windows) or [download](https://github.com/woodser/monero-java/releases/tag/v0.8.13) the Windows native libraries to the ./build folder.
4. Open TestMoneroUtils.java and click the button to run `testGetIntegratedAddresses()`.
5. The test should succeed, but instead fails with `UnsatisfiedLinkError`:

![image](https://github.com/woodser/monero-java/assets/13068859/798eb8f7-5c43-40e8-bdf7-82dc65dc6ad8)

**Comment by everoddandeven** [comment]
I'm trying to debug, it seems that libmonero-java.dll failed to load other dlls

**Comment by everoddandeven** [comment]
I just put C:\msys64\mingw64\bin the Path environment variable and now it works:

![image](https://github.com/woodser/monero-java/assets/59447913/6ff8e7b7-b794-43b9-8dea-9fb545ce9318)

**Comment by woodser** [comment]
How did you add it to the path?

I tried in Windows command prompt: `set PATH=C:\msys64\mingw64\bin;%PATH%`

But I'm still seeing the same error in VS Code.

**Comment by woodser** [comment]
Hm, I tried adding C:\msys64\mingw64\bin to the Path environment variable, but I'm still getting the UnsatisfiedLinkError running the test in VS Code.

Dependency walker looks much better after adding to Path, though:

<img width="996" alt="image" src="https://github.com/woodser/monero-java/assets/13068859/3929fd24-f511-435e-884b-36adea8d2f05">
